version: '3.4'

services:
  catalogdb:
    image: mongo

  microservices.kata.catalog.api:
    image: ${DOCKER_REGISTRY-}microserviceskatacatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Microservices.Kata.Catalog.API/Dockerfile

volumes:
  mongo_data: